import React, { createContext, useContext, useState, useEffect } from 'react';

export type Lang = 'en' | 'he';

const translations = {
  en: {
    // Nav
    recipeBuilder:       'Recipe Builder',
    kitchenRecipes:      'Kitchen Recipes',
    buildNewRecipe:      'Build new recipe',
    kitchenRecipesEmpty: 'No recipes yet. Click "Build new recipe" to start.',
    prepStepsSection:    'Preparation steps',
    noPrepSteps:         'No preparation steps for this recipe.',
    prepStepsFromBase:   'Preparation steps (from the base recipe)',
    optional:            'optional',
    stepLabel:           'Step',
    stepNameLabel:       'Step name:',
    processExplanation:  'Process explanation',
    addStep:             'Add step',
    removeStep:          'Remove step',
    testRecipes:         'Test Recipes',
    testBadge:           'TEST',
    testRecipesHint:     'Recipes still in development — not in the real lists. A manager promotes a finished one.',
    testRecipesEmpty:    'No test recipes yet. Click "Build new recipe" to start.',
    testRedColumn:       'Missing',
    testMissingTag:      'not in catalogue',
    testRedTooltip:      'Ingredients not yet in the catalogue (red). Create them in Odoo and sync.',
    testDeleted:         'Test recipe deleted',
    addNewProductRed:    "Add \"{name}\" as a new product",
    adhocRefPlaceholder: 'SKU (optional)',
    promoteToReal:       'Promote',
    promoteBlockedRed:   'Resolve all red ingredients first (create them in Odoo + sync).',
    promoteConfirm:      'Promote "{name}" into the real recipe list?',
    promoteDone:         'Recipe promoted to the real list',
    promoteFailed:       'Promote failed',
    submitForApproval:       'Send this recipe to the final recipes',
    submitForApprovalConfirm:'Are you sure you want to send this recipe for approval?',
    submitForApprovalDone:   'Recipe sent for approval',
    submitForApprovalFailed: 'Submit failed',
    submitSaveFirst:         'Save your changes first, then send for approval.',
    pendingApproval:         'Pending Approval',
    pendingApprovalHint:     'Recipes submitted for approval. Approve once no ingredient is red.',
    pendingApprovalEmpty:    'No recipes are waiting for approval.',
    pendFilterLabel:         'Filter by status',
    pendFilterAll:           'All',
    pendFilterReady:         'Ready',
    pendFilterIssues:        'Has issues',
    pendFilterEmpty:         'No recipes match this filter.',
    bulkApproving:           'Approving {n} recipes… this can take a moment.',
    approveRecipe:           'Approve',
    approveConfirm:          'Approve "{name}" and move it to the real recipe list?',
    sendBackBtn:             'Send back for re-editing',
    sendBackNoteLabel:       'What needs completing:',
    sendBackNotePlaceholder: 'e.g. missing image, fix quantities…',
    sendBackConfirm:         'Send back',
    sendBackDone:            'Recipe sent back for re-editing',
    sendBackFailed:          'Send-back failed',
    settings:            'Settings',
    bomHistory:          'BOM History',
    baseRecipes:         'Base Recipes',
    finalProducts:       'Final Products',
    // Recipe type toggle
    recipeTypeLabel:     'Recipe Type',
    baseRecipeOption:    'Base Recipe',
    finalProductOption:  'Final Packaged Product',
    startFromBase:       'Start from a base recipe',
    pickBaseRecipe:      'Pick a base recipe…',
    baseRecipeHint:      'Adds the base recipe as a linked sub-recipe and copies its code, ingredients and preparation steps. You can then add packaging and extra steps.',
    // App header
    bomSystem:           'BOM & Recipe System',
    productionMgmt:      'Production Management',
    // Recipe Builder
    recipeName:          'Recipe Name',
    recipeNamePlaceholder:'e.g. Croissant Dough',
    referenceCode:       'Reference Code',
    yieldKg:             'Yield (KG)',
    ingredient:          'Ingredient Name',
    qty:                 'QTY (KG)',
    costPerKg:           'Cost per KG',
    costPerUnit:         'Cost per unit',
    saleUomLabel:        'Sold per',
    saleUomKg:           'Kilogram (kg)',
    saleUomUnit:         'Unit',
    lineCost:            'Line Cost',
    totals:              'Totals',
    addIngredient:       '+ Add Ingredient',
    clear:               'Clear',
    // Kitchen Recipes — view toggle + bulk actions
    viewMode:            'View',
    viewCards:           'Card view',
    viewList:            'List view',
    viewArchived:        'Archived',
    viewActive:          'Active',
    restore:             'Restore',
    bulkRestored:        '{n} recipe(s) restored',
    archiveEmpty:        'No archived recipes.',
    archive:             'Archive',
    recipe:              'recipe',
    recipes:             'recipes',
    bulkSelected:        '{n} selected',
    bulkConfirmDelete:   'Permanently delete {n} selected recipe(s)? This cannot be undone. To keep them but hide them, use Archive instead.',
    bulkConfirmArchive:  'Move {n} selected recipe(s) to the archive? They stay saved but are hidden from the list.',
    bulkDeleted:         '{n} recipe(s) deleted',
    bulkArchived:        '{n} recipe(s) archived',
    bulkBlocked:         '{n} could not be deleted — still used as a sub-recipe in other recipes (archive them instead).',
    confirmDeleteRecipe: 'Permanently delete "{name}"? This cannot be undone.',
    recipeDeleted:       'Recipe permanently deleted',
    deleteFailed:        'Could not delete the recipe',
    deleteInUse:         'This recipe is used as a sub-recipe in another recipe. Remove it there first, or archive it instead.',
    saveRecipe:          'Save Recipe',
    saving:              'Saving…',
    searchPlaceholder:   'Search ingredient or recipe…',
    noResults:           'No results found',
    searching:           'Searching…',
    subRecipe:           'Sub-Recipe',
    openBaseRecipe:      'Open the full base recipe',
    openIngredient:      'Open ingredient page',
    raw:                 'Raw',
    // Production costs
    productionCosts:     'Production Costs',
    perBatch:            'per batch',
    labor:               'Labor',
    overhead:            'Overhead',
    totalProduction:     'Total Production',
    productionCostsBreakdown: 'Production costs per batch:',
    // Live preview bar
    livePreview:         'Live Preview',
    totalRecipeCost:     'Total Recipe Cost',
    yieldLabel:          'Yield',
    // Table headers
    ofCostPct:           '% of Cost',
    wastePct:            'Waste %',
    // Header fields
    pricingStrategy:     'Pricing Strategy',
    autoCalculate:       'Auto-Calculate (Recommended)',
    // Misc
    unsavedChanges:      'Unsaved changes',
    // Formula Manager
    pricingFormulas:     'Pricing Formula Manager',
    addUpdateFormula:    'Add / Update Formula',
    formulaBuilderHint:  'Build a price formula freely with the variable "cost" and the operators + − × ÷ and ( ). Example: cost × 1.5 × 1.07.',
    formulaLabel:        'Formula',
    formulaVarCost:      'cost',
    formulaVat:          'VAT',
    formulaVatHint:      'Multiply by 1.07 (adds 7% VAT)',
    formulaMargin:       'margin',
    formulaRoundUp:      'Round up',
    formulaRoundDown:    'Round down',
    formulaRoundUpHint:  'Round the whole formula UP to a whole number, e.g. roundup(cost * 1.5). Use roundup(…, 1) for 1 decimal.',
    formulaRoundDownHint:'Round the whole formula DOWN to a whole number, e.g. rounddown(cost * 1.5).',
    formulaRoundUp5:     'Round up to 5',
    formulaRoundUp5Hint: 'Round the whole formula UP to the next multiple of 5, e.g. roundupto(cost * 1.5, 5). Change the 5 to 10 etc. for other steps.',
    scope:               'Scope',
    scopeId:             'Scope ID',
    category:            'Category',
    wholesaleMult:       'Wholesale Multiplier',
    retailMult:          'Retail Multiplier',
    wholesaleMargin:     'Wholesale margin',
    retailMargin:        'Retail margin',
    saveFormula:         'Save Formula',
    selectCategory:      '— select category —',
    formulaDefault:      'Default',
    formulaSetDefault:   'Set as default',
    formulaDefaultBadge: 'DEFAULT',
    formulaCannotDeleteDefault: 'Cannot delete the default formula. Mark another formula as default first.',
    // BOM History
    bomHistoryTitle:     'BOM History',
    bomHistoryDesc:      'Cost-change logs and BOM revision history will appear here.',
    refCode:             'Ref Code',
    linesHeader:         'Lines',
    ver:                 'Ver.',
    lastUpdated:         'Last Updated',
    actions:             'Actions',
    edit:                'Edit',
    delete:              'Delete',
    noSavedRecipes:      'No saved recipes yet. Build and save your first recipe.',
    loading:             'Loading…',
    failedToLoad:        'Failed to load BOM history.',
    // Import / Export toolbar
    rioSearchPlaceholder:    'Search by name or code…',
    rioFromDate:             'From',
    rioToDate:               'To',
    rioClearFilters:         'Clear filters',
    rioSelectedCount:        '{n} selected',
    rioImportBtn:            'Import',
    rioExportBtn:            'Export',
    rioTemplateBtn:          'Download template',
    rioExportSelected:       'Export selected',
    rioExportFiltered:       'Export filtered',
    rioExportFailed:         'Export failed',
    rioTemplateFailed:       'Could not download the template.',
    rioNoRowsToExport:       'No recipes match the current filters.',
    rioRecipesShown:         '{n} of {total} recipes',
    // Import modal
    rioImportTitle:          'Import recipes from Excel',
    rioImportSubtitle:       'Upload a .xlsx prepared from the template. One row per ingredient; recipe-level fields on the first row of each recipe.',
    rioDropFileHere:         'Drop your .xlsx file here',
    rioOrBrowse:             'or click to browse',
    rioFileSelected:         'File selected',
    rioFileRemove:           'Remove',
    rioOnDuplicateLabel:     'If a recipe with the same name or code already exists',
    rioOnDuplicateUpdate:    'Update it (new version)',
    rioOnDuplicateSkip:      'Skip it',
    rioDefaultTypeLabel:     'Default Recipe Type when not specified in the file',
    rioStartImport:          'Start import',
    rioImporting:            'Importing…',
    rioCancel:               'Cancel',
    rioClose:                'Close',
    rioDownloadTemplateLink: 'Download the template',
    // Import report
    rioReportTitle:          'Import results',
    rioReportTotal:          'Total',
    rioReportCreated:        'Created',
    rioReportUpdated:        'Updated',
    rioReportSkipped:        'Skipped',
    rioReportFailed:         'Failed',
    rioReportRow:            'Row',
    rioReportName:           'Recipe',
    rioReportStatus:         'Status',
    rioReportMessage:        'Details',
    rioReportEmpty:          'No recipes were processed.',
    rioReportImported:       '{n} of {total} recipes imported successfully.',
    rioReportClickHint:      'Click a card above to filter the list by status.',
    rioImportFailedTitle:    'Import failed',
    // Where Used (Traceability)
    whereUsed:                 'Where Used',
    whereUsedTitle:            'Where Used — Traceability',
    whereUsedDesc:             'Find all recipes that use a specific ingredient or sub-assembly anywhere in their BOM tree.',
    whereUsedSearchPlaceholder:'Search by name or reference code…',
    whereUsedNoSelection:      'Search for an ingredient or sub-assembly above to see which recipes use it.',
    whereUsedNotUsed:          'This item is not used in any active recipe.',
    whereUsedRecipeCol:        'Recipe',
    whereUsedDepthCol:         'Depth',
    whereUsedDirect:           'direct',
    whereUsedLevels:           'levels',
    whereUsedNotFound:         'Item not found.',
    whereUsedUsedInPre:        'is used in',
    whereUsedUsedInPost:       'recipe',
    whereUsedUsedInPlural:     'recipes',
    // Validation errors
    validationErrorTitle:  'Please fix the following errors before saving',
    missingRecipeName:     'Recipe Name is required.',
    missingReferenceCode:  'Reference Code is required.',
    invalidYield:          'Yield must be a number greater than 0.',
    emptyIngredients:      'Add at least one ingredient.',
    invalidIngredientRow:  'Each ingredient row must have a selected item and a quantity greater than 0.',
    // Final products list pricing columns
    totalCost:           'Total Cost',
    tkpPrice:            'TKP Price',
    sellingPrice:        'Selling Price',
    // Generic
    noFormulas:          'No formulas configured yet — add one below.',
    // Login page
    loginTitle:          'Sign In',
    loginSubtitle:       'BOM & Recipe Management System',
    loginUsername:       'Username',
    loginUsernamePh:     'Enter your username',
    loginCode:           'System Code',
    loginCodePh:         'Enter your system code',
    loginButton:         'Sign In',
    loginLoading:        'Signing in…',
    loginError:          'Invalid username or code. Please try again.',
    logout:              'Sign Out',
    // Recipe Book (customer-facing)
    recipeBook:              'Recipe Book',
    recipeBookSubtitle:      'Browse recipes, scale to any batch size, and print prep sheets.',
    rbSearchPlaceholder:     'Search recipes by name or reference…',
    rbFilterAll:             'All',
    rbFilterCategory:        'Category',
    rbFilterAllergen:         'Allergen',
    rbFilterSpicy:           'Spicy only',
    rbSpicyTag:              'Spicy',
    rbAllergenLabel:         'Contains',
    rbNoRecipes:             'No recipes match your filters.',
    rbServings:              'Servings',
    rbServingSuggestion:     'Serving suggestion',
    rbTotalWeight:           'Net weight',
    rbViewRecipe:            'Open',
    rbBackToList:            '← Back to Recipe Book',
    back:                    'Back',
    rbIngredientsHeader:     'Ingredients',
    rbQuantityHeader:        'Quantity',
    rbWasteHeader:           'Waste',
    rbCostPerKgHeader:       'Cost / kg',
    rbLineCostHeader:        'Line cost',
    rbBatchCostsLabel:       'Per-batch additions',
    // Calculator
    calcTitle:               'Scale this recipe',
    calcDesiredWeight:       'How much to produce (kg)',
    calcRun:                 'Calculate',
    calcRunning:             'Calculating…',
    calcEnoughForServings:   'Enough for ~{n} servings',
    calcResultTitle:         'Scaled batch',
    calcScaleFactor:         'Scale factor',
    calcMaterialCost:        'Materials',
    calcLabor:               'Labor',
    calcOverhead:            'Overhead',
    calcPackaging:           'Packaging',
    calcTotalCost:           'Total cost',
    calcWholesaleTotal:      'Wholesale total',
    calcRetailTotal:         'Retail total',
    calcShoppingList:        'Aggregated shopping list',
    calcShoppingListNote:    'Total raw-material quantities across all sub-recipes.',
    calcSubRecipeOf:         'Sub-recipe',
    calcNoPriceData:         'Price information is hidden for your account.',
    calcPrintPrepSheet:      'Print prep sheet',
    calcPrintingTitle:       'Prep Sheet',
    calcEnterAmount:         'Enter a target weight to see scaled quantities.',
    calcFormulaApplied:      'Formula applied',
    calcManualOverride:      'manual override',
    calcAutoSelection:       'auto-selected',
    // Admin: Dashboard / Logs / Users / Sync
    dashboard:               'Dashboard',
    dashboardWelcome:        'Overview',
    dashSummaryBase:         'Base recipes',
    dashSummaryFinal:        'Final products',
    dashSummaryProducts:     'Raw materials (Odoo)',
    dashSummaryPending:      'Pending approval',
    dashSummaryTest:         'Test recipes (draft)',
    dashSummaryUsers:        'Team (managers + admins)',
    dashArchived:            'archived',
    dashSummaryAdmins:       'Admins',
    dashSummaryCustomers:    'Customers',
    dashSummaryInactive:     'Inactive users',
    dashLastSync:            'Last Odoo sync',
    dashSyncOk:              'Last sync succeeded',
    dashSyncFailed:          'Last sync failed',
    dashSyncNever:           'No sync recorded yet',
    dashQuickActions:        'Quick actions',
    users:                   'Users',
    usersTitle:              'User Management',
    usersDesc:               'Promote / demote users, override price visibility, or deactivate access.  Authentication itself stays in Odoo — these settings only affect this app.',
    userColRole:             'Role',
    userColUser:             'User',
    userColCanViewPrices:    'Can view prices',
    userColActive:           'Active',
    userColLastLogin:        'Last login',
    userColActions:          'Actions',
    userCvpDefault:          'Default (role-based)',
    userCvpYes:              'Yes',
    userCvpNo:               'No',
    userActivate:            'Activate',
    userDeactivate:          'Deactivate',
    userEditTitle:           'Edit user',
    userEditName:            'Display name',
    userEditUsername:        'Username',
    userEditPw:              'New password (leave blank to keep)',
    userEditSave:            'Save',
    userEditCancel:          'Cancel',
    userUsernameTaken:       'That username is already taken. Choose a different one.',
    userSavePending:         'Saving…',
    userCreateTitle:         'Create new user',
    userCreateBtn:           'Create user',
    userCreated:             'User created',
    userCreateFailed:        'Could not create user',
    userPwPlaceholder:       'Password',
    userNamePlaceholder:     'Display name (optional)',
    userPwHint:              'Password must be at least 6 characters. The user logs in with this username + password.',
    logs:                    'Logs',
    logsTitle:               'Audit Log',
    logsDesc:                'Login events, user changes, pricing-formula edits, sync runs and customer calculations.',
    logsExportCsv:           'Export CSV',
    logsActionType:          'Action type',
    logsUser:                'User',
    logsFrom:                'From',
    logsTo:                  'To',
    logsApplyFilter:         'Apply',
    logsClearFilter:         'Clear',
    logsColTime:             'Timestamp',
    logsColUser:             'User',
    logsColAction:           'Action',
    logsColEntity:           'Entity',
    logsColDescription:      'Description',
    logsColIp:               'IP',
    logsNoRows:              'No log entries match the current filters.',
    logsShowingCount:        'Showing {n} of {total}',
    odooSync:                'Odoo Sync',
    odooSyncDesc:            'The cron job runs every {schedule}.  Trigger a manual sync below if you just updated products in Odoo.',
    odooSyncManual:          'Run sync now',
    odooSyncRunning:         'Syncing… this can take 30s+',
    odooSyncDoneToast:       'Odoo sync complete',
    odooSyncFailToast:       'Odoo sync failed',
    odooSyncRecalc:          'Recalculate all recipe costs',
    odooSyncRecalcDoneToast: 'Cost recalculation complete',
    odooSyncCronSchedule:    'Cron schedule',
    odooSyncActiveProducts:  'Active raw materials',
    odooSyncLastTrigger:     'Last triggered',
    odooSyncLastOutcome:     'Last outcome',
    rbStalePinWarning:       'Selected formula no longer exists — fell back to the default formula.',
    rbFormulaSection:        'Pricing formula',
    rbFormulaAuto:           'Use default formula',
    rbFormulaActiveLabel:    'Currently applied',
    // Recipe Book extra fields shown in builder
    rbFieldFullName:         'Display name (full title)',
    rbFieldDescription:      'Description',
    rbFieldAllergens:        'Allergens (comma-separated)',
    rbFieldIsSpicy:          'Spicy',
    rbFieldServingSuggestion:'Serving suggestion',
    rbFieldServingsCount:    'Servings per yield',
    rbFieldTotalWeight:      'Total net weight (kg)',
    rbBrandingSection:       'Recipe-book card',
    rbFieldImageHint:        'Click to upload image',
    rbViewPrint:             'Print',
    pdf:                     'PDF',
    rbViewPdf:               'PDF',
    rbViewPrintTitle:        'Print or save as PDF',
    settingsTabFormulas:     'Pricing formulas',
    settingsTabUsers:        'Users',
    settingsTabSync:         'Odoo sync',
    settingsTabRefCodes:     'Reference codes',
    settingsTabPermissions:  'Permissions',
    permTitle:               'Menu permissions per role',
    permHint:                'Choose which sidebar tabs each role can see. Changes save automatically. (Manager always keeps Settings.)',
    permTab:                 'Tab',
    permSaved:               'Permissions saved',
    role_customer:           'Staff',
    role_admin:              'Manager',
    role_manager:            'Kitchen Manager',
    noTabAccess:             'No tabs are assigned to your role. Please contact a manager.',
    profileTab:              'Personal area',
    profileTitle:            'Personal area',
    profileName:             'Display name',
    profileUsername:         'Username',
    profileSave:             'Save profile',
    profileSaved:            'Profile saved',
    profileSaveFailed:       'Save failed',
    profileChangePhoto:      'Change photo',
    profileRemovePhoto:      'Remove photo',
    profileChangePw:         'Change password',
    profileNewPw:            'New password',
    profileConfirmPw:        'Confirm password',
    profilePwChanged:        'Password changed',
    profilePwMismatch:       'Passwords do not match',
    profileRole:             'Role',
    // Reference-code categories (Settings → Reference codes)
    refCodesTitle:           'Reference-code categories',
    refCodesDesc:            'Define code categories (prefixes). New recipes pick a category and the system auto-fills the next free number, e.g. BAK-0001.',
    refCodeAdd:              'Add a category',
    refCodeAddBtn:           'Add',
    refCodePrefix:           'Prefix',
    refCodeDescription:      'Description',
    refCodeHint:             'Prefix must be 3–5 uppercase English letters (e.g. BAK, CAKE, BREAD).',
    refCodesEmpty:           'No categories yet. Add one above.',
    refCodeSaved:            'Category saved',
    refCodeSaveFailed:       'Could not save the category',
    refCodeInvalidPrefix:    'Prefix must be 3–5 uppercase English letters.',
    refCodeCategorySelect:   'Pick a category…',
    refCodeNextFailed:       'Could not get the next code',
    importCodesExistTitle:   'Reference codes already exist',
    importCodesExistDesc:    'These reference codes already exist in the system. Change them in your file and upload again — nothing was imported.',
    formulaNameLabel:        'Formula name',
    formulaPriorityLabel:    'Priority',
    // Products tab (admin-only Odoo catalogue)
    products:                'Products',
    productsTitle:           'Products — Odoo Catalogue',
    productsSearchPlaceholder: 'Search by name or reference…',
    productsSortHint:        'Click to sort',
    productsResizeHint:      'Drag to resize column',
    productsColImage:        'Image',
    productsColName:         'Product name',
    productsColWeight:       'Weight (Odoo)',
    productsColCost:         'Cost',
    productsColCostPerKg:    'Cost / kg',
    productsWeightMissing:   'Weight missing — cannot compute',
    productsCpkStored:       'Showing stored cost_per_kg from items table',
    productsCpkComputed:     'Computed live: raw_cost / weight (g) × 1000',
    productsCpkStoredTag:    'stored',
    productsCpkComputedTag:  'computed',
    productsEmpty:           'No raw-material products synced yet.',
    productsNoMatches:       'No products match the current search.',
    productsEstimatedFromName: 'Estimated from name',
    productsEstimatedTag:    'estimated',
    productsWeightFromRegex: 'Weight parsed from product name (no Odoo weight)',
    productsCpkFromRegex:    'Cost-per-kg uses name-extracted weight (estimated)',
    // Per-litre / per-unit measures + the raw-cost fallback
    productsMeasureVolume:   'litre',
    productsMeasureCount:    'unit',
    productsCpkPerLitre:     'Cost per litre (parsed "l"/"lt" from name)',
    productsCpkPerUnit:      'Cost per unit (parsed "unit" from name)',
    productsCpkRawCostTag:   'cost',
    productsCpkRawCost:      'No weight/measure found — using the cost price as cost-per-kg',
    // Manual override / inline editing
    productsColActions:      '',
    productsEdit:            'Edit',
    productsSave:            'Save',
    productsCancel:          'Cancel',
    productsManualTag:       'manual',
    productsCpkManual:       'Manually overridden value',
    productsEditTitle:       'Manual override',
    productsEditCost:        'Cost price',
    productsEditWeight:      'Weight (kg)',
    productsEditCpk:         'Cost / kg',
    productsEditHint:        'Leave a field blank to use the automatic value.',
    productsSaved:           'Product updated',
    productsSaveFailed:      'Failed to update product',
    productsIncludeArchived: 'Include archived products',
    productsArchivedTag:     'archived',
    productsArchivedTitle:   'Archived in Odoo',
  },
  he: {
    // Nav
    recipeBuilder:       'בניית מתכון',
    kitchenRecipes:      'מתכוני מטבח',
    buildNewRecipe:      'בנה מתכון חדש',
    kitchenRecipesEmpty: 'אין עדיין מתכונים. לחצו "בנה מתכון חדש" כדי להתחיל.',
    prepStepsSection:    'שלבי ההכנה',
    noPrepSteps:         'אין שלבי הכנה למתכון זה.',
    prepStepsFromBase:   'שלבי ההכנה (מהמתכון הבסיס)',
    optional:            'רשות',
    stepLabel:           'שלב',
    stepNameLabel:       'שם השלב:',
    processExplanation:  'הסבר התהליך',
    addStep:             'הוספת שלב',
    removeStep:          'הסרת שלב',
    testRecipes:         'מתכוני טסט',
    testBadge:           'טסט',
    testRecipesHint:     'מתכונים בבדיקה — לא ברשימות האמיתיות. מנהל מעביר מתכון מוכן.',
    testRecipesEmpty:    'אין עדיין מתכוני טסט. לחצו "בנה מתכון חדש" כדי להתחיל.',
    testRedColumn:       'חסרים',
    testMissingTag:      'לא בקטלוג',
    testRedTooltip:      'מרכיבים שעדיין לא קיימים בקטלוג (אדום). צרו אותם באודו ובצעו סנכרון.',
    testDeleted:         'מתכון הטסט נמחק',
    addNewProductRed:    'הוסף את "{name}" כמוצר חדש',
    adhocRefPlaceholder: 'מק"ט (אופציונלי)',
    promoteToReal:       'אישור והעברה',
    promoteBlockedRed:   'יש לפתור קודם את כל המרכיבים האדומים (ליצור באודו + לסנכרן).',
    promoteConfirm:      'להעביר את "{name}" לרשימת המתכונים האמיתית?',
    promoteDone:         'המתכון הועבר לרשימה האמיתית',
    promoteFailed:       'ההעברה נכשלה',
    submitForApproval:       'שלח מתכון זה למתכונים הסופיים',
    submitForApprovalConfirm:'האם אתה בטוח שברצונך לשלוח מתכון זה לאישור?',
    submitForApprovalDone:   'המתכון נשלח לאישור',
    submitForApprovalFailed: 'השליחה נכשלה',
    submitSaveFirst:         'שמור קודם את השינויים ואז שלח לאישור.',
    pendingApproval:         'מתכונים ממתינים לאישור',
    pendingApprovalHint:     'מתכונים שנשלחו לאישור. אשר כאשר אין מרכיב אדום.',
    pendingApprovalEmpty:    'אין מתכונים הממתינים לאישור.',
    pendFilterLabel:         'סינון לפי סטטוס',
    pendFilterAll:           'הכול',
    pendFilterReady:         'מוכן לאישור',
    pendFilterIssues:        'עם תקלות',
    pendFilterEmpty:         'אין מתכונים שתואמים לסינון.',
    bulkApproving:           'מאשר {n} מתכונים… זה עשוי לקחת רגע.',
    approveRecipe:           'אישור',
    approveConfirm:          'לאשר את "{name}" ולהעביר לרשימת המתכונים האמיתית?',
    sendBackBtn:             'שלח לעריכה מחדש',
    sendBackNoteLabel:       'מה צריך להשלים:',
    sendBackNotePlaceholder: 'למשל: חסרה תמונה, לתקן כמויות…',
    sendBackConfirm:         'שלח חזרה',
    sendBackDone:            'המתכון נשלח לעריכה מחדש',
    sendBackFailed:          'השליחה נכשלה',
    settings:            'הגדרות',
    bomHistory:          'היסטוריית BOM',
    baseRecipes:         'מתכוני בסיס',
    finalProducts:       'מוצרים סופיים',
    // Recipe type toggle
    recipeTypeLabel:     'סוג מתכון',
    baseRecipeOption:    'מתכון בסיס',
    finalProductOption:  'מוצר ארוז סופי',
    startFromBase:       'התחל ממתכון בסיס',
    pickBaseRecipe:      'בחרי מתכון בסיס…',
    baseRecipeHint:      'מוסיף את מתכון הבסיס כתת-מתכון מקושר ומעתיק את הקוד, הרכיבים ושלבי ההכנה. אפשר להוסיף אחר כך אריזה ושלבים נוספים.',
    // App header
    bomSystem:           'מערכת BOM ומתכונים',
    productionMgmt:      'ניהול ייצור',
    // Recipe Builder
    recipeName:          'שם המתכון',
    recipeNamePlaceholder:'לדוגמה: בצק קרואסון',
    referenceCode:       'קוד אסמכתה',
    yieldKg:             'תפוקה (ק"ג)',
    ingredient:          'שם המרכיב',
    qty:                 'כמות (ק"ג)',
    costPerKg:           'עלות לק"ג',
    costPerUnit:         'עלות ליחידה',
    saleUomLabel:        'נמכר לפי',
    saleUomKg:           'קילוגרם (ק"ג)',
    saleUomUnit:         'יחידה',
    lineCost:            'עלות שורה',
    totals:              'סכומים',
    addIngredient:       '+ הוסף מרכיב',
    clear:               'נקה',
    // מתכוני מטבח — מתג תצוגה + פעולות קבוצתיות
    viewMode:            'תצוגה',
    viewCards:           'תצוגת כרטיסיות',
    viewList:            'תצוגת רשימה',
    viewArchived:        'ארכיון',
    viewActive:          'פעילים',
    restore:             'שחזור',
    bulkRestored:        '{n} מתכונים שוחזרו',
    archiveEmpty:        'אין מתכונים בארכיון.',
    archive:             'ארכיון',
    recipe:              'מתכון',
    recipes:             'מתכונים',
    bulkSelected:        '{n} נבחרו',
    bulkConfirmDelete:   'למחוק לצמיתות {n} מתכונים שנבחרו? לא ניתן לבטל. כדי לשמור אותם ולהסתיר — השתמשי ב"ארכיון".',
    bulkConfirmArchive:  'להעביר {n} מתכונים שנבחרו לארכיון? הם יישמרו אך יוסתרו מהרשימה.',
    bulkDeleted:         '{n} מתכונים נמחקו',
    bulkArchived:        '{n} מתכונים הועברו לארכיון',
    bulkBlocked:         '{n} לא נמחקו — הם עדיין בשימוש כתת-מתכון במתכונים אחרים (העבירי אותם לארכיון במקום).',
    confirmDeleteRecipe: 'למחוק לצמיתות את "{name}"? לא ניתן לבטל.',
    recipeDeleted:       'המתכון נמחק לצמיתות',
    deleteFailed:        'לא ניתן למחוק את המתכון',
    deleteInUse:         'המתכון בשימוש כתת-מתכון במתכון אחר. הסירי אותו משם קודם, או העבירי לארכיון.',
    saveRecipe:          'שמור מתכון',
    saving:              'שומר…',
    searchPlaceholder:   'חפש מרכיב או מתכון...',
    noResults:           'לא נמצאו תוצאות',
    searching:           'מחפש…',
    subRecipe:           'תת-מתכון',
    openBaseRecipe:      'פתח את מתכון הבסיס המלא',
    openIngredient:      'פתח את עמוד הרכיב',
    raw:                 'חומר גלם',
    // Production costs
    productionCosts:     'עלויות ייצור',
    perBatch:            'לאצווה',
    labor:               'עבודה',
    overhead:            'הוצאות עקיפות',
    totalProduction:     'סה"כ ייצור',
    productionCostsBreakdown: 'עלויות ייצור לאצווה:',
    // Live preview bar
    livePreview:         'תצוגה חיה',
    totalRecipeCost:     'עלות מתכון כוללת',
    yieldLabel:          'תפוקה',
    // Table headers
    ofCostPct:           '% מהעלות',
    wastePct:            'פחת %',
    // Header fields
    pricingStrategy:     'אסטרטגיית תמחור',
    autoCalculate:       'חישוב אוטומטי (מומלץ)',
    // Misc
    unsavedChanges:      'שינויים שלא נשמרו',
    // Formula Manager
    pricingFormulas:     'מנהל נוסחאות תמחור',
    addUpdateFormula:    'הוסף / עדכן נוסחה',
    formulaBuilderHint:  'בנו נוסחת מחיר חופשית עם המשתנה "cost" (עלות) והפעולות + − × ÷ וסוגריים ( ). לדוגמה: cost × 1.5 × 1.07.',
    formulaLabel:        'נוסחה',
    formulaVarCost:      'עלות',
    formulaVat:          'מע"מ',
    formulaVatHint:      'הכפלה ב-1.07 (מוסיף 7% מע"מ)',
    formulaMargin:       'רווח',
    formulaRoundUp:      'עיגול למעלה',
    formulaRoundDown:    'עיגול למטה',
    formulaRoundUpHint:  'מעגל את כל הנוסחה כלפי מעלה למספר שלם, למשל roundup(cost * 1.5). לעיגול לספרה עשרונית: roundup(…, 1).',
    formulaRoundDownHint:'מעגל את כל הנוסחה כלפי מטה למספר שלם, למשל rounddown(cost * 1.5).',
    formulaRoundUp5:     'עיגול למעלה ל-5',
    formulaRoundUp5Hint: 'מעגל את כל הנוסחה כלפי מעלה לכפולה הקרובה של 5, למשל roundupto(cost * 1.5, 5). אפשר לשנות את ה-5 ל-10 וכו\'.',
    scope:               'היקף',
    scopeId:             'מזהה היקף',
    category:            'קטגוריה',
    wholesaleMult:       'מכפיל סיטונאי',
    retailMult:          'מכפיל קמעוני',
    wholesaleMargin:     'שולי סיטונאי',
    retailMargin:        'שולי קמעוני',
    saveFormula:         'שמור נוסחה',
    selectCategory:      '— בחר קטגוריה —',
    formulaDefault:      'ברירת מחדל',
    formulaSetDefault:   'הגדר כברירת מחדל',
    formulaDefaultBadge: 'ברירת מחדל',
    formulaCannotDeleteDefault: 'לא ניתן למחוק את נוסחת ברירת המחדל. סמן נוסחה אחרת כברירת מחדל תחילה.',
    // BOM History
    bomHistoryTitle:     'היסטוריית BOM',
    bomHistoryDesc:      'יומני שינויי עלויות והיסטוריית גרסאות BOM יופיעו כאן.',
    refCode:             'קוד אסמכתה',
    linesHeader:         'שורות',
    ver:                 'גרסה',
    lastUpdated:         'עדכון אחרון',
    actions:             'פעולות',
    edit:                'ערוך',
    delete:              'מחק',
    noSavedRecipes:      'אין מתכונים שמורים עדיין. בנה ושמור את המתכון הראשון שלך.',
    loading:             'טוען…',
    failedToLoad:        'טעינת היסטוריית BOM נכשלה.',
    // Import / Export toolbar
    rioSearchPlaceholder:    'חיפוש לפי שם או קוד…',
    rioFromDate:             'מתאריך',
    rioToDate:               'עד תאריך',
    rioClearFilters:         'נקה סינון',
    rioSelectedCount:        '{n} מסומנים',
    rioImportBtn:            'ייבוא',
    rioExportBtn:            'ייצוא',
    rioTemplateBtn:          'הורד קובץ דוגמה',
    rioExportSelected:       'ייצוא המסומנים',
    rioExportFiltered:       'ייצוא המסונן',
    rioExportFailed:         'הייצוא נכשל',
    rioTemplateFailed:       'לא ניתן היה להוריד את הקובץ.',
    rioNoRowsToExport:       'אין מתכונים שתואמים לסינון.',
    rioRecipesShown:         '{n} מתוך {total} מתכונים',
    // Import modal
    rioImportTitle:          'ייבוא מתכונים מאקסל',
    rioImportSubtitle:       'העלה קובץ .xlsx שהוכן לפי הדוגמה. שורה אחת לכל רכיב; שדות המתכון בשורה הראשונה של כל מתכון.',
    rioDropFileHere:         'גרור את קובץ ה-xlsx לכאן',
    rioOrBrowse:             'או לחץ לבחירת קובץ',
    rioFileSelected:         'הקובץ נבחר',
    rioFileRemove:           'הסר',
    rioOnDuplicateLabel:     'אם מתכון עם אותו שם או קוד כבר קיים',
    rioOnDuplicateUpdate:    'עדכן אותו (גרסה חדשה)',
    rioOnDuplicateSkip:      'דלג עליו',
    rioDefaultTypeLabel:     'סוג מתכון ברירת מחדל כשלא צוין בקובץ',
    rioStartImport:          'התחל ייבוא',
    rioImporting:            'מייבא…',
    rioCancel:               'ביטול',
    rioClose:                'סגירה',
    rioDownloadTemplateLink: 'הורד קובץ דוגמה',
    // Import report
    rioReportTitle:          'תוצאות הייבוא',
    rioReportTotal:          'סה"כ',
    rioReportCreated:        'נוצרו',
    rioReportUpdated:        'עודכנו',
    rioReportSkipped:        'דולגו',
    rioReportFailed:         'נכשלו',
    rioReportRow:            'שורה',
    rioReportName:           'מתכון',
    rioReportStatus:         'סטטוס',
    rioReportMessage:        'פרטים',
    rioReportEmpty:          'לא עובדו מתכונים.',
    rioReportImported:       '{n} מתוך {total} מתכונים יובאו בהצלחה.',
    rioReportClickHint:      'לחצו על כרטיסיה למעלה כדי לסנן את הרשימה לפי סטטוס.',
    rioImportFailedTitle:    'הייבוא נכשל',
    // Where Used (Traceability)
    whereUsed:                 'שימוש ברכיבים',
    whereUsedTitle:            'שימוש ברכיבים — מעקב',
    whereUsedDesc:             'מצא את כל המתכונים שמשתמשים ברכיב מסוים או תת-הרכבה בכל עץ ה-BOM שלהם.',
    whereUsedSearchPlaceholder:'חפש לפי שם או קוד אסמכתה…',
    whereUsedNoSelection:      'חפש מרכיב או תת-הרכבה כדי לראות אילו מתכונים משתמשים בו.',
    whereUsedNotUsed:          'פריט זה לא נמצא בשימוש באף מתכון פעיל.',
    whereUsedRecipeCol:        'מתכון',
    whereUsedDepthCol:         'עומק',
    whereUsedDirect:           'ישיר',
    whereUsedLevels:           'רמות',
    whereUsedNotFound:         'פריט לא נמצא.',
    whereUsedUsedInPre:        'משמש ב-',
    whereUsedUsedInPost:       'מתכון',
    whereUsedUsedInPlural:     'מתכונים',
    // Validation errors
    validationErrorTitle:  'נא תקן את השגיאות הבאות לפני השמירה',
    missingRecipeName:     'שם המתכון נדרש.',
    missingReferenceCode:  'קוד אסמכתה נדרש.',
    invalidYield:          'התפוקה חייבת להיות מספר גדול מ-0.',
    emptyIngredients:      'הוסף לפחות מרכיב אחד.',
    invalidIngredientRow:  'לכל שורת מרכיב חייב להיות פריט נבחר וכמות גדולה מ-0.',
    // Final products list pricing columns
    totalCost:           'מחיר עלות',
    tkpPrice:            'מחיר TKP',
    sellingPrice:        'מחיר מכירה',
    // Generic
    noFormulas:          'אין נוסחאות מוגדרות עדיין — הוסף אחת למטה.',
    // Login page
    loginTitle:          'כניסה למערכת',
    loginSubtitle:       'מערכת BOM וניהול מתכונים',
    loginUsername:       'שם משתמש',
    loginUsernamePh:     'הכנס שם משתמש',
    loginCode:           'קוד כניסה',
    loginCodePh:         'הכנס את קוד המערכת',
    loginButton:         'כניסה',
    loginLoading:        'מתחבר…',
    loginError:          'שם משתמש או קוד שגוי. אנא נסה שוב.',
    logout:              'יציאה',
    // Recipe Book (customer-facing)
    recipeBook:              'ספר המתכונים',
    recipeBookSubtitle:      'דפדף במתכונים, שנה גודל אצווה והדפס דפי הכנה.',
    rbSearchPlaceholder:     'חפש מתכון לפי שם או קוד אסמכתה…',
    rbFilterAll:             'הכל',
    rbFilterCategory:        'קטגוריה',
    rbFilterAllergen:        'אלרגן',
    rbFilterSpicy:           'חריף בלבד',
    rbSpicyTag:              'חריף',
    rbAllergenLabel:         'מכיל',
    rbNoRecipes:             'לא נמצאו מתכונים תואמים לסינון.',
    rbServings:              'מנות',
    rbServingSuggestion:     'הצעת הגשה',
    rbTotalWeight:           'משקל נטו',
    rbViewRecipe:            'פתח',
    rbBackToList:            '→ חזרה לספר המתכונים',
    back:                    'חזרה',
    rbIngredientsHeader:     'מרכיבים',
    rbQuantityHeader:        'כמות',
    rbWasteHeader:           'פחת',
    rbCostPerKgHeader:       'עלות / ק"ג',
    rbLineCostHeader:        'עלות שורה',
    rbBatchCostsLabel:       'תוספות לאצווה',
    // Calculator
    calcTitle:               'התאם גודל אצווה',
    calcDesiredWeight:       'כמה לייצר (ק״ג)',
    calcRun:                 'חשב',
    calcRunning:             'מחשב…',
    calcEnoughForServings:   'מספיק ל-~{n} מנות',
    calcResultTitle:         'אצווה מותאמת',
    calcScaleFactor:         'מקדם התאמה',
    calcMaterialCost:        'חומרי גלם',
    calcLabor:               'עבודה',
    calcOverhead:            'הוצאות',
    calcPackaging:           'אריזה',
    calcTotalCost:           'עלות כוללת',
    calcWholesaleTotal:      'סיטונאי כולל',
    calcRetailTotal:         'קמעוני כולל',
    calcShoppingList:        'רשימת קניות מצטברת',
    calcShoppingListNote:    'סך כמויות חומרי גלם בכל תתי-המתכונים.',
    calcSubRecipeOf:         'תת-מתכון',
    calcNoPriceData:         'מידע מחיר מוסתר עבור החשבון שלך.',
    calcPrintPrepSheet:      'הדפס דף הכנה',
    calcPrintingTitle:       'דף הכנה',
    calcEnterAmount:         'הזן משקל יעד כדי לראות כמויות מותאמות.',
    calcFormulaApplied:      'נוסחה הוחלה',
    calcManualOverride:      'עקיפה ידנית',
    calcAutoSelection:       'נבחר אוטומטית',
    // Admin: Dashboard / Logs / Users / Sync
    dashboard:               'לוח בקרה',
    dashboardWelcome:        'סקירה',
    dashSummaryBase:         'מתכוני בסיס',
    dashSummaryFinal:        'מוצרים סופיים',
    dashSummaryProducts:     'חומרי גלם (אודו)',
    dashSummaryPending:      'ממתינים לאישור',
    dashSummaryTest:         'מתכוני טסט (טיוטה)',
    dashSummaryUsers:        'צוות (מנהלים + אדמינים)',
    dashArchived:            'בארכיון',
    dashSummaryAdmins:       'מנהלים',
    dashSummaryCustomers:    'לקוחות',
    dashSummaryInactive:     'משתמשים לא פעילים',
    dashLastSync:            'סנכרון אחרון מאודו',
    dashSyncOk:              'סנכרון אחרון הצליח',
    dashSyncFailed:          'סנכרון אחרון נכשל',
    dashSyncNever:           'אין סנכרון רשום',
    dashQuickActions:        'פעולות מהירות',
    users:                   'משתמשים',
    usersTitle:              'ניהול משתמשים',
    usersDesc:               'קדם/הורד משתמשים, עקוף נראות מחירים או השבת גישה.  האימות עצמו נשאר באודו — ההגדרות כאן משפיעות רק על אפליקציה זו.',
    userColRole:             'תפקיד',
    userColUser:             'משתמש',
    userColCanViewPrices:    'רואה מחירים',
    userColActive:           'פעיל',
    userColLastLogin:        'כניסה אחרונה',
    userColActions:          'פעולות',
    userCvpDefault:          'ברירת מחדל (לפי תפקיד)',
    userCvpYes:              'כן',
    userCvpNo:               'לא',
    userActivate:            'הפעל',
    userDeactivate:          'השבת',
    userEditTitle:           'עריכת משתמש',
    userEditName:            'שם תצוגה',
    userEditUsername:        'שם משתמש',
    userEditPw:              'סיסמה חדשה (השאר ריק כדי לא לשנות)',
    userEditSave:            'שמירה',
    userEditCancel:          'ביטול',
    userUsernameTaken:       'שם המשתמש כבר תפוס. בחרו שם אחר.',
    userSavePending:         'שומר…',
    userCreateTitle:         'יצירת משתמש חדש',
    userCreateBtn:           'צור משתמש',
    userCreated:             'המשתמש נוצר',
    userCreateFailed:        'יצירת המשתמש נכשלה',
    userPwPlaceholder:       'סיסמה',
    userNamePlaceholder:     'שם תצוגה (אופציונלי)',
    userPwHint:              'הסיסמה חייבת להיות לפחות 6 תווים. המשתמש מתחבר עם שם המשתמש והסיסמה האלה.',
    logs:                    'יומנים',
    logsTitle:               'יומן ביקורת',
    logsDesc:                'אירועי כניסה, שינויי משתמשים, עריכת נוסחאות תמחור, ריצות סנכרון וחישובי לקוח.',
    logsExportCsv:           'יצא ל-CSV',
    logsActionType:          'סוג פעולה',
    logsUser:                'משתמש',
    logsFrom:                'מתאריך',
    logsTo:                  'עד תאריך',
    logsApplyFilter:         'החל',
    logsClearFilter:         'נקה',
    logsColTime:             'זמן',
    logsColUser:             'משתמש',
    logsColAction:           'פעולה',
    logsColEntity:           'ישות',
    logsColDescription:      'תיאור',
    logsColIp:               'IP',
    logsNoRows:              'אין רשומות יומן התואמות לסינון.',
    logsShowingCount:        'מציג {n} מתוך {total}',
    odooSync:                'סנכרון אודו',
    odooSyncDesc:            'משימת ה-cron רצה כל {schedule}.  הפעל סנכרון ידני אם עדכנת מוצרים באודו.',
    odooSyncManual:          'הרץ סנכרון עכשיו',
    odooSyncRunning:         'מסנכרן… יכול לקחת 30 שניות',
    odooSyncDoneToast:       'סנכרון אודו הסתיים',
    odooSyncFailToast:       'סנכרון אודו נכשל',
    odooSyncRecalc:          'חשב מחדש את כל עלויות המתכונים',
    odooSyncRecalcDoneToast: 'חישוב מחדש של עלויות הסתיים',
    odooSyncCronSchedule:    'לוח זמני cron',
    odooSyncActiveProducts:  'חומרי גלם פעילים',
    odooSyncLastTrigger:     'הופעל לאחרונה',
    odooSyncLastOutcome:     'תוצאה אחרונה',
    rbStalePinWarning:       'הנוסחה הנבחרת לא קיימת — חזר לנוסחת ברירת המחדל.',
    rbFormulaSection:        'נוסחת תמחור',
    rbFormulaAuto:           'השתמש בנוסחת ברירת המחדל',
    rbFormulaActiveLabel:    'פעיל כעת',
    // Recipe Book extra fields shown in builder
    rbFieldFullName:         'שם תצוגה (כותרת מלאה)',
    rbFieldDescription:      'תיאור',
    rbFieldAllergens:        'אלרגנים (מופרדים בפסיק)',
    rbFieldIsSpicy:          'חריף',
    rbFieldServingSuggestion:'הצעת הגשה',
    rbFieldServingsCount:    'מנות לתפוקה',
    rbFieldTotalWeight:      'משקל נטו כולל (ק״ג)',
    rbBrandingSection:       'כרטיס ספר מתכונים',
    rbFieldImageHint:        'לחצי להעלאת תמונה',
    rbViewPrint:             'הדפסה',
    pdf:                     'PDF',
    rbViewPdf:               'PDF',
    rbViewPrintTitle:        'הדפסה או שמירה כ-PDF',
    settingsTabFormulas:     'נוסחאות תמחור',
    settingsTabUsers:        'משתמשים',
    settingsTabSync:         'סנכרון אודו',
    settingsTabRefCodes:     'קודי ייחוס',
    settingsTabPermissions:  'הרשאות',
    permTitle:               'הרשאות תפריט לפי תפקיד',
    permHint:                'בחרו אילו לשוניות בתפריט הצד כל תפקיד יכול לראות. השינויים נשמרים אוטומטית. (מנהל תמיד נשאר עם ההגדרות.)',
    permTab:                 'לשונית',
    permSaved:               'ההרשאות נשמרו',
    role_customer:           'צוות עובדים',
    role_admin:              'מנהל',
    role_manager:            'מנהלי מטבח',
    noTabAccess:             'לא הוקצו לשוניות לתפקיד שלך. פנו למנהל.',
    profileTab:              'אזור אישי',
    profileTitle:            'אזור אישי',
    profileName:             'שם לתצוגה',
    profileUsername:         'שם משתמש',
    profileSave:             'שמירת פרופיל',
    profileSaved:            'הפרופיל נשמר',
    profileSaveFailed:       'השמירה נכשלה',
    profileChangePhoto:      'החלפת תמונה',
    profileRemovePhoto:      'הסרת תמונה',
    profileChangePw:         'שינוי סיסמה',
    profileNewPw:            'סיסמה חדשה',
    profileConfirmPw:        'אימות סיסמה',
    profilePwChanged:        'הסיסמה שונתה',
    profilePwMismatch:       'הסיסמאות אינן תואמות',
    profileRole:             'תפקיד',
    // קטגוריות קוד ייחוס (הגדרות → קודי ייחוס)
    refCodesTitle:           'קטגוריות קוד ייחוס',
    refCodesDesc:            'הגדירו קטגוריות קוד (קידומות). מתכון חדש בוחר קטגוריה והמערכת ממלאת אוטומטית את המספר הפנוי הבא, לדוגמה BAK-0001.',
    refCodeAdd:              'הוספת קטגוריה',
    refCodeAddBtn:           'הוספה',
    refCodePrefix:           'קידומת',
    refCodeDescription:      'תיאור',
    refCodeHint:             'הקידומת חייבת להיות 3–5 אותיות אנגליות גדולות (לדוגמה BAK, CAKE, BREAD).',
    refCodesEmpty:           'אין עדיין קטגוריות. הוסיפו אחת למעלה.',
    refCodeSaved:            'הקטגוריה נשמרה',
    refCodeSaveFailed:       'לא ניתן לשמור את הקטגוריה',
    refCodeInvalidPrefix:    'הקידומת חייבת להיות 3–5 אותיות אנגליות גדולות.',
    refCodeCategorySelect:   'בחרו קטגוריה…',
    refCodeNextFailed:       'לא ניתן לקבל את הקוד הבא',
    importCodesExistTitle:   'קודי ייחוס כבר קיימים',
    importCodesExistDesc:    'קודי הייחוס הבאים כבר קיימים במערכת. שנו אותם בקובץ והעלו שוב — שום דבר לא יובא.',
    formulaNameLabel:        'שם הנוסחה',
    formulaPriorityLabel:    'עדיפות',
    // Products tab (admin-only Odoo catalogue)
    products:                'מוצרים',
    productsTitle:           'מוצרים — קטלוג אודו',
    productsSearchPlaceholder: 'חפש לפי שם או קוד אסמכתה…',
    productsSortHint:        'לחץ למיון',
    productsResizeHint:      'גררו לשינוי רוחב העמודה',
    productsColImage:        'תמונה',
    productsColName:         'שם המוצר',
    productsColWeight:       'משקל (אודו)',
    productsColCost:         'עלות',
    productsColCostPerKg:    'עלות / ק״ג',
    productsWeightMissing:   'משקל חסר — לא ניתן לחשב',
    productsCpkStored:       'מציג cost_per_kg שמור מטבלת items',
    productsCpkComputed:     'חישוב חי: raw_cost / משקל (גרם) × 1000',
    productsCpkStoredTag:    'שמור',
    productsCpkComputedTag:  'חי',
    productsEmpty:           'אין חומרי גלם מסונכרנים עדיין.',
    productsNoMatches:       'אין מוצרים תואמים לחיפוש.',
    productsEstimatedFromName: 'מוערך משם המוצר',
    productsEstimatedTag:    'מוערך',
    productsWeightFromRegex: 'המשקל חולץ משם המוצר (לא מאודו)',
    productsCpkFromRegex:    'עלות/ק״ג מבוססת על משקל שחולץ מהשם (הערכה)',
    // מחיר לליטר / ליחידה + נפילה למחיר העלות
    productsMeasureVolume:   'ליטר',
    productsMeasureCount:    'יחידה',
    productsCpkPerLitre:     'מחיר לליטר ("l"/"lt" חולץ מהשם)',
    productsCpkPerUnit:      'מחיר ליחידה ("unit" חולץ מהשם)',
    productsCpkRawCostTag:   'עלות',
    productsCpkRawCost:      'לא נמצא משקל/מידה — מוצג מחיר העלות כעלות לק״ג',
    // עריכה ידנית
    productsColActions:      '',
    productsEdit:            'עריכה',
    productsSave:            'שמירה',
    productsCancel:          'ביטול',
    productsManualTag:       'ידני',
    productsCpkManual:       'ערך שהוזן ידנית',
    productsEditTitle:       'עריכה ידנית',
    productsEditCost:        'מחיר עלות',
    productsEditWeight:      'משקל (ק״ג)',
    productsEditCpk:         'עלות / ק״ג',
    productsEditHint:        'השאר שדה ריק כדי להשתמש בערך האוטומטי.',
    productsSaved:           'המוצר עודכן',
    productsSaveFailed:      'עדכון המוצר נכשל',
    productsIncludeArchived: 'כולל מוצרים מהארכיון',
    productsArchivedTag:     'בארכיון',
    productsArchivedTitle:   'מאורכב באודו',
  },
} as const;

// Translations type covers both langs.  We widen each value to `string`
// so EN-vs-HE literal differences don't cause an assignability error
// at the <Provider> boundary, while keeping the EN key-set as the
// authoritative shape (any missing key surfaces as a property error).
export type Translations = { readonly [K in keyof typeof translations['en']]: string };

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue>({
  lang: 'en',
  setLang: () => {},
  t: translations.en,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('bom_lang') as Lang) ?? 'en';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('bom_lang', l);
  };

  useEffect(() => {
    document.documentElement.setAttribute('dir',  lang === 'he' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang === 'he' ? 'he'  : 'en');
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
